builds:
  - id: darwin-amd64
    main: ./cmd/nibid
    binary: nibid
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}
