name: chaosnet

services:
  nibiru:
    build:
      context: ../.. # nibiru project folder
      dockerfile: ./contrib/docker/localnet.Dockerfile # relative to context directory (i.e. nibiru project folder)
      args:
        MNEMONIC: guard cream sadness conduct invite crumble clock pudding hole grit liar hotel maid produce squeeze return argue turtle know drive eight casino maze host
    ports:
      - 26656:26656
      - 26657:26657
      - 1317:1317
      - 9090:9090

  faucet:
    image: ghcr.io/nibiruchain/go-faucet:latest
    environment:
      NODE: nibiru:9090
      MNEMONIC: guard cream sadness conduct invite crumble clock pudding hole grit liar hotel maid produce squeeze return argue turtle know drive eight casino maze host
      SEND_COINS: 11000000unibi,100000000unusd,100000000uusdt
      MAX_SEND_COINS: 110000000unibi,1000000000unusd,1000000000uusdt
    depends_on:
      - nibiru
    restart: on-failure
    ports:
      - 8000:8000

  liquidation-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: liquidator
    ports:
      - 5433:5432

  liquidator:
    image: ghcr.io/nibiruchain/liquidation:latest
    platform: linux/amd64 # see https://github.com/psycopg/psycopg2/issues/1360 for why we need to force linux/amd64
    restart: always
    environment:
      - ENVIRONMENT=localnet
      - NETWORK_INSECURE=true
      - CHAIN_ID=nibiru-localnet-0
      - LCD_ENDPOINT=http://nibiru:1317
      - GRPC_ENDPOINT=nibiru:9090
      - RPC_ENDPOINT=nibiru:26657
      - WEBSOCKET_ENDPOINT=ws://nibiru:26657/websocket
      - DATABASE_URI=postgresql+psycopg2://postgres:postgres@liquidation-db:5432/liquidator
      - WALLET_MNEMONIC=guard cream sadness conduct invite crumble clock pudding hole grit liar hotel maid produce squeeze return argue turtle know drive eight casino maze host
      - VPOOLS=ubtc:unusd

  heart-monitor-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: heart-monitor
    ports:
      - 5434:5432

  heart-monitor:
    image: ghcr.io/nibiruchain/heart-monitor:latest
    platform: linux/amd64 # see https://github.com/psycopg/psycopg2/issues/1360 for why we need to force linux/amd64
    restart: always
    environment:
      - DATABASE_URI=postgresql+psycopg2://postgres:postgres@heart-monitor-db:5432/heart-monitor
      - ENVIRONMENT=localnet
      - NETWORK_INSECURE=true
      - LCD_ENDPOINT=http://nibiru:1317
      - GRPC_ENDPOINT=tcp://nibiru:9090
      - TENDERMINT_RPC_ENDPOINT=http://nibiru:26657
      - WEBSOCKET_ENDPOINT=ws://nibiru:26657/websocket
      - VALIDATOR_MNEMONIC=guard cream sadness conduct invite crumble clock pudding hole grit liar hotel maid produce squeeze return argue turtle know drive eight casino maze host
      - MODULE_ACCOUNTS={'nibi1yl6hdjhmkf37639730gffanpzndzdpmhe6js7s':'transfer','nibi1fl48vsnmsdzcv85q5d2q4z5ajdha8yu3z7dksy':'bonded_tokens_pool','nibi1trh2mamq64u4g042zfeevvjk4cukrthvppfnc7':'perp_ef','nibi1tygms3xhhs3yv487phx3dw4a95jn7t7lk738xs':'not_bonded_tokens_pool','nibi10d07y265gmmuvt4z0w9aw880jnsr700jd8hulq':'gov','nibi1jv65s3grqf6v6jl3dp4t6c9t9rk99cd8s6q9qv':'distribution','nibi143kdcynewz7d08fmlu0ugtnn9sv8vljxwp7eug':'fee_pool','nibi1m3h30wlvsf8llruxtpukdvsy0km2kum8l5rpwn':'mint','nibi1umc2r7a58jy3jmw0e0hctyy0rx45chmurptawl':'vault','nibi17xpfvakm2amg962yls6f84z3kell8c5l8u8ezw':'fee_collector'}
      - LOGGER_TIMESTAMP=true

  pricefeeder:
    image: ghcr.io/nibiruchain/pricefeeder:0.0.7
    restart: always
    environment:
      CHAIN_ID: "nibiru-localnet-0"
      GRPC_ENDPOINT: nibiru:9090
      WEBSOCKET_ENDPOINT: ws://nibiru:26657/websocket
      FEEDER_MNEMONIC: guard cream sadness conduct invite crumble clock pudding hole grit liar hotel maid produce squeeze return argue turtle know drive eight casino maze host
      EXCHANGE_SYMBOLS_MAP: '{ "bitfinex": { "ubtc:uusd": "tBTCUSD", "ueth:uusd": "tETHUSD", "uusdt:uusd": "tUSTUSD" }, "binance": { "ubtc:uusd": "BTCUSD", "ueth:uusd": "ETHUSD", "uusdt:uusd": "USDTUSD", "uusdc:uusd": "USDCUSD", "uatom:uusd": "ATOMUSD", "ubnb:uusd": "BNBUSD", "uavax:uusd": "AVAXUSD", "usol:uusd": "SOLUSD", "uada:uusd": "ADAUSD", "ubtc:unusd": "BTCUSD", "ueth:unusd": "ETHUSD", "uusdt:unusd": "USDTUSD", "uusdc:unusd": "USDCUSD", "uatom:unusd": "ATOMUSD", "ubnb:unusd": "BNBUSD", "uavax:unusd": "AVAXUSD", "usol:unusd": "SOLUSD", "uada:unusd": "ADAUSD" } }'

    depends_on:
      nibiru:
        condition: service_started

volumes:
  bdjuno-repo:
  bdjuno-docker-entrypoint:
  bdjuno-genesis:
  bdjuno-hasura-metadata:
